freckle/freckle-app

frontrow-app.cabal, library/FrontRow/App/Http.hs, library/FrontRow/App/Http/Paginate.hs, library/FrontRow/App/Http/Retry.hs, package.yaml
This creates a `FrontRow.App.Http` module tree to (hopefully) serve our needs for making HTTP calls to 3rd parties from any of our backend apps.
- `FrontRow.App.Http`: top-level interface, uses/re-exports from below, hopefully serves 95% cases
- `FrontRow.App.Http.Paginate`: conduit-based pagination interface, drop here if you need special behavior (e.g. _not_ via `Link`)
- `FrontRow.App.Http.Retry`: handling of 429-`Retry-In`, unlikely to be independently useful, mostly isolated for organizational tidiness
Modules attempt to be well-documented and rich enough to support all use-cases I found in our backend so far; with the exception of CSV, which, to be honest, I don't remember why I didn't add it at this stage, but we can add it now or later easily.
The module is …
=> FrontRow.App.Http

.editorconfig, frontrow-app.cabal, library/FrontRow/App/Http.hs, package.yaml, tests/FrontRow/App/HttpSpec.hs
**NOTE**: This PR include two options:
- aa2aa0d95edfb47d5cb6b9a4387127a7acffc4dd Remove the e from HttpDecodeErrors
*This is the option I'm proposing, the end-state of this diff, and so I am
including the full commit message:*
`HttpDecodeError String` doesn't have an `Exception` instance, because there
is no Exception instance for String. Therefore, `getResponseBodyUnsafe` didn't
work with `httpJson`, which was basically its entire purpose.
To fix this, we make `HttpDecodeError` hold a `String` internally and ask
callers to marshal it themselves by passing `ByteString-> (Either (NonEmpty
String) a` to `httpDecode`.
Alternatives considered:
1. Use a `newtype` as necessary in each decoding case
For example, an `AesonDecodeError` wrapper over `String` with an
`Exception` instance that just …
=> Address HttpDecodeError and the lack of Exception(String)

library/FrontRow/App/Http.hs, tests/FrontRow/App/HttpSpec.hs
Users of `getResponseBodyUnsafe` are typically just looking for a successful
value and to crash otherwise. For unsuccessful responses, the body was unlikely
to parse as they expected, but throwing whatever is the `Left` error hides the
fact that it was unsuccessful to begin with.
This patch will throw a new `HttpStatusError` instead. It still holds the
`Either` response body, so access to all the same information is still present;
the error should just be clearer.
This doesn't change `getResponseBody`, which will return whatever body is there
(`Either` or not) regardless of status. The assumption is that, if you are going
to check the body for `Either` yourself, you can/will also check
`statusIsSuccessful . getResponseStatus` too. For this expected usage, I added
`statusIsSuccessful` to …
=> Throw HttpStatusError first in getResponseBodyUnsafe

library/FrontRow/App/Http.hs, tests/FrontRow/App/HttpSpec.hs
When I tried to use `HttpStatusError` it didn't go well; so I'm pulling that out
and doing something much smaller in scope to see how that goes instead.
Because of the polymorphism of the response body, it was actually impossible to
catch and handle an exception of this type without knowing the concrete response
body we're trying to decode to, which made it impossible for my use-case.
In trying to correct that (which basically means forcing it to `Response ()`), I
found myself literally re-implementing `setRequestCheckStatus`. Therefore, I'm
reverting that other attempt and adding a note to just use that function (which
I'm also re-exporting for that purpose) when that's the behavior you want, which
is what I plan to do where I needed this.
=> Revert HttpStatusError, expose setRequestCheckStatus

frontrow-app.cabal, library/FrontRow/App/Database.hs, library/FrontRow/App/Time.hs, package.yaml
[Add statement timeout to Jobs](https://app.asana.com/0/13211253278157/1200281325971161/f)
We goofed by allowing an application indefinite transaction/statement times. Ideally we could offer configuration for both transaction and statement timeouts here eventually, but the statement level is easy enough to support via PG statement configuration.There is also PG's `idle_in_transaction_session_timeout` which we might be able to leverage if we need further granularity in the future.
=> Add optional statement timeout to runDB

library/FrontRow/App/Database.hs
Bug fix
Parsing of this field is broken currently when it is provided, because of weird behavior between `Prelude.read` with `Maybe`. Instead we should try to parse a non-`Maybe` `Seconds` field, and rely on `optional` to do the `Maybe` work for us.
cc @StevenXL who apparently got into a discussion with Pat on Reddit about this once :upside_down_face:
=> Fix parsing of optional statement timeout

frontrow-app.cabal, library/FrontRow/App/Http.hs, library/FrontRow/App/Http/Retry.hs, package.yaml
We decided early on that `FrontRow.App.Http` would not throw exceptions
for non-2XX statuses by default. We did this by using
`setRequestIgnoreStatus` in the base request runner (`httpLbs`).
This was a design choice, but also practically necessary because
`rateLimited` does not function if 429s cause immediate exceptions.
However, the way we did that made it impossible to recover the other
behavior when desired. Any use of `setRequestCheckStatus` would be ignored
because we nope it out deeper down the chain. Users have no recourse
other than explicitly checking status and throwing.
Worse, they can't re-use (or even re-implement!) any of
`Network.Http.Conduit`'s machinery for that check because it is all typed
`Response ReadBody`, which we have lost by the time we've run the request
to …
=> Relax use of setRequestIgnoreStatus

library/FrontRow/App/Http.hs
https://app.asana.com/0/1199344717368182/1200421645749559/f is requiring setting some `x-www-form-urlencoded` `POST` request body.
This exposes the function `Network.HTTP.Simple.setRequestBodyURLEncoded` to do so
=> Add an export for setRequestBodyURLEncoded

CHANGELOG.md, freckle-app.cabal, package.yaml
Ensure that `Release` GitHub Action completes. Note that this has no code changes, and thus uses the "additional component" in [Haskell PVP](https://pvp.haskell.org/), which states:
"A package version number SHOULD have the form A.B.C, and MAY optionally have any number of additional components, for example 2.1.0.4 (in this case, A=2, B=1, C=0). This policy defines the meaning of the first three components A-C, the other components can be used in any way the package maintainer sees fit"
=> Ensure that `Release` GitHub Action completes.

CHANGELOG.md, freckle-app.cabal, package.yaml
New release. This will allow us to add `freckle-app` on stackage without having to ignore the test suite (hopefully).
=> Extract tests that require `git` into new suite.

freckle-app.cabal, package.yaml
This will include `package.yaml` in the tarball that is uploaded to
hackage. See
[comment](https://github.com/commercialhaskell/stackage/issues/6172#issuecomment-907842852).
=> Add `package.yaml` to `extra-source-files`.

CHANGELOG.md, library/Freckle/App/Yesod.hs
When the `statement_timeout` set by `Freckle.App.Database` triggers, we get this
`SqlError`. By attaching one of these functions as `yesodMiddleware`, we can
turn that into a 503.
The function also logs, increments a DogStats metric, and supports attaching
headers (necessary for our AuthorizationChecked machinery).
=> Add function for responding 503 on query-cancelled

CHANGELOG.md, library/Freckle/App/Wai.hs
Increments generic metrics, expecting that the environment will use tags to
disambiguate (e.g. app:fancy-api).
=> Add Request Metrics Middleware

freckle-app.cabal, library/Freckle/App/Datadog.hs, library/Freckle/App/Datadog/Gauge.hs, library/Freckle/App/RtsStats.hs
We still have a need for a stateful gauge in our application. There is
no reason to re-implement EKG's `Atomic`, so instead we can encapsulate
it and our associated use patterns.
=> Encapsulate EKG gauges

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Datadog/Rts.hs, package.yaml
This is a minor version release via PVP rules.
- Added `Freckle.App.Datadog.Gauge` for client side stateful gauges.
- Added `Freckle.App.Datadog.Rts` for sending RTS statistics to DataDog.
=> Release 1.0.1.0

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Yesod/Route.hs, library/Freckle/App/Yesod/Routes.hs, package.yaml
Yesod handles dispatch through abstract types and template haskell.
These opaque `Route a` types makes it hard to traverse the data without
manually unrolling the entire tree yourself. Instead we can use the same
methods that `yesod` uses internally to traverse `ResourceTree` and
produce the function from the route file itself.
This template haskell is pretty tame, it just builds a gigantic lambda
case expression nesting all of the routes and returning the leaf route
name at the end.
Other solutions are possible since we hold onto all `Static` and
`Dynamic` path names in the route file, but this method matches our
current use of `____R` resource names.
=> Use Template Haskell to produce routes names

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Wai.hs, package.yaml, tests/Freckle/App/WaiSpec.hs
From the task
The "X-Frame-Options" header controls which origins are allowed to iframe the current page. The lack of this header can make many attacks such as XSS, CSRF, and Client-Side Account Takeover much more easily exploitable. Without the "X- Frame-Options" header it is also possible to perform click-jacking attacks which may have high impact depending on the application.
It is recommended that the "X-Frame-Options" be added to the response headers throughout the application in order to prevent easy exploitation of client-side bugs and click-jacking.
=> Add middleware for denying all HTML frame embedding

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Test/Hspec/Runner.hs, package.yaml, stack.yaml, stack.yaml.lock
This version removed `runJUnitSpec` in favor of functions better-suited to the
common case (e.g. `hspecJUnit`). This, however, is not the common case.
We are running three suites separately and evaluating everything once at the
end. Therefore, we have to dig around in hspec internals a little more and
re-implement `runJUNitSpec` ourselves.
=> Update to hspec-unit-formatter-1.1.0.0

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Database.hs, library/Freckle/App/Datadog.hs, library/Freckle/App/Datadog/Gauge.hs, library/Freckle/App/Datadog/Rts.hs, library/Freckle/App/Env.hs, library/Freckle/App/Env/Internal.hs, library/Freckle/App/Ghci.hs, library/Freckle/App/GlobalCache.hs, library/Freckle/App/Http.hs, library/Freckle/App/Http/Paginate.hs, library/Freckle/App/Http/Retry.hs, library/Freckle/App/Logging.hs, library/Freckle/App/Prelude.hs, library/Freckle/App/RIO.hs, library/Freckle/App/Test.hs, library/Freckle/App/Test/DocTest.hs, library/Freckle/App/Test/Hspec/Runner.hs, library/Freckle/App/Version.hs, library/Freckle/App/Wai.hs, library/Freckle/App/Yesod.hs, library/Freckle/App/Yesod/Routes.hs, package.yaml
**Why?**
In removing `classy-prelude` from our monorepo, a ton of import ergonomics have
been lost. This attempts to recover some of those ergonomics and also be the
starting point for our very own prelude.
This was mostly inspired by the things I had to import a gazillion types when
removing `classy-prelude` from a few of our libraries. Before hitting the
library that has the most instances, I thought it'd be nice to have something
like this in place.
**Things to look out for**
- Did I export too much?
- Are there glaring omissions?
- Did I pick the wrong thing in some case (e.g. is `Control.Monad.Reader` the
- "right" reader?)
- Should this move into our monorepo?
- Should I get a dep from another package? All new packages were hidden deps, which is nice, but should I have instead just …
=> Add Freckle-specific prelude

library/Freckle/App/Database.hs
This hard-coded region prevents deploys of `freckle-app` backed by IAM auth outside of `us-east-1`. We can remove it and allow for region discovery in AWS environments to populate as desired (assuming co-location of the deployment with the target DB).
=> Remove explicit region specification in DB token generation

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Env.hs, library/Freckle/App/Http/Paginate.hs, library/Freckle/App/Logging.hs, library/Freckle/App/Prelude.hs, library/Freckle/App/Test/Hspec/Runner.hs, library/Freckle/App/Version.hs, library/Freckle/App/Wai.hs, library/Freckle/App/Yesod.hs, package.yaml
These were discussed in backend guild as being common enough that we should
include them in `Freckle.App.Prelude`.
=> Add some common textual encoding functions to prelude

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Wai.hs, package.yaml
By accepting a generic producer of [(Text, Text)], callers can supply
the same route (and trace_id) values we are using today, but also be
able to supply any others (without blowing up the interface).
Concretely, this will be used to add a Freckle Team as the "owner" tag
to everything we emit from our Haskell APIs.
=> Simplify getRouteName, getTraceId to getTags

library/Freckle/App/Database.hs
We've found that such a small default leads to lockups even in a low
traffic environment such as local development.
Closes #40.
=> Change PGPOOLSIZE default

freckle-app.cabal, library/Freckle/App/Bugsnag.hs, package.yaml, stack-lts-12.26.yaml, stack-lts-12.26.yaml.lock, stack-lts-14.27.yaml, stack-lts-14.27.yaml.lock, stack-lts-16.31.yaml, stack-lts-16.31.yaml.lock, stack-lts-18.28.yaml, stack-lts-18.28.yaml.lock, stack-nightly.yaml, stack-nightly.yaml.lock, stack.yaml, stack.yaml.lock, tests/Freckle/App/BugsnagSpec.hs
This commit includes a variety of Bugsnag supports for freckle apps.
- Parsing env variables.
- Refined grouping of common exceptions (http, sql).
- Standard `beforeNotify` hooks to add refinements.
These have been extracted from Freckle's applications with domain
specific logic removed.
=> Migrate Bugsnag handling

library/Freckle/App/Test/Logging.hs
Occasionally the Memcacached spec fails because we don't see the final
log message. I traced this down to Test.Logging cancelling the
asynchronous loop reading them too eagerly.
This patch uses a sentinel final message so the draining loop will
always wait long enough and the test shouldn't flake.
=> Fix Test.Logging race condition

freckle-app.cabal, library/Freckle/App/Test/Logging.hs, package.yaml, tests/Freckle/App/MemcachedSpec.hs
- Make the interface `[LogLine]`, like [`runWriterLoggingT`][rwlt]
- Store messages in a `DList`, like `runWriterLoggingT` does
- Update comment to indicate why we can't just use `runWriterLoggingT`
[rwlt]: https://hackage.haskell.org/package/monad-logger-0.3.36/docs/Control-Monad-Logger.html#v:runWriterLoggingT
=> Refactor runCapturedLoggingT

freckle-app.cabal, library/Freckle/App/Database.hs, library/Freckle/App/Ghci.hs, library/Freckle/App/Version.hs, package.yaml
This is how it is meant to work: creation of the pool captures the
logging context and will use it to log database activity. Doing this
allowed us to address some TODOs for logging token handling as well. I
also removed some TODOs that were _TODONE_ already, and some dead code.
To recover the previous behavior, end-users can import and use
`runNoLoggingT` themselves; but they are encouraged to use their real
logging context instead.
=> Run Database pool creation in MonadLogger

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Env.hs, package.yaml, stack-nightly.yaml, stack-nightly.yaml.lock
Immediately after implementing `kept`, [envparse-0.5](https://hackage.haskell.org/package/envparse-0.5.0) was released and
Stackage nightly picked it up. In order to stay, we need to be
compatible.
Should fix https://github.com/commercialhaskell/stackage/issues/6614
=> Compatibility with envparse-0.5.0

CHANGELOG.md, freckle-app.cabal, package.yaml, stack-lts-12.26.yaml, stack-lts-12.26.yaml.lock, stack-lts-14.27.yaml, stack-lts-14.27.yaml.lock
When I added this, I mistakenly used the latest primitive (0.7.4.0) and
not the minimum as required by aeson (0.7.0.1). This is particularly
problematic because our oldest snapshot sets our lower bounds on
release, so we ended up shipping with a very high lower-bound on
primitive and we're being held out of Stackage because of it.
=> Use older primitive extra-dep

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Stats.hs, package.yaml
The automatic adding of tags to the thread context doesn't work for a
web application that forks a new thread (with an empty context) for
every request.
This can be solved pretty easily by setting up the context yourself in a
WAI middleware, but it requires pulling the tags off of the app type,
and so we need a function to access them.
The existing Lens function maintains encapsulation and
composes well with `statsClientL`:
```hs
statsTags :: HasStatsClient env => env -> [(Text, Text)]
statsTags = app ^.. statsClientL . tagsL . traverse
```
This can be used with a Middleware like `addThreadContext` from Blammo.
=> Export tagsL

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Bugsnag.hs, package.yaml
A timeout can happen basically anywhere, so having them all grouped
together is not useful for triaging. Segregating them at least by
Request URL would be an improvement for us. Note that if the Request or
URL is missing, we fall back to grouping them all together. This means
you should ensure the `updateEventFromWaiRequest` `BeforeNotify` runs
before this one.
=> Group SqlError Timeouts by Request URL

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Bugsnag.hs, package.yaml
Query strings will vary from call to call, especially because we include
an `echo` GET param that is unique to every request. This means we'd be
effectively making unique timeout Errors every time.
Naively stripping the query string works (vs parsing the URL), since
we're not using this for anything critical, and will ensure this groups
by domain-path only. Hashes should not be involved for a Backend API,
though we could strip that too if we find cases.
=> Drop query string from URL used to group timeouts

CHANGELOG.md, library/Freckle/App/Bugsnag.hs, package.yaml
The CHANGELOG says it best:
Consider `/foos/1` vs `/foos/2`: grouping naively by `url` makes these two
errors when we wanted them to be one. This can't be solved without knowledge
of the routing system, so we can't do it from within this library as-is.
Therefore, we've reverted the feature for now.
=> Revert regrouping of SqlError by url

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Database.hs, package.yaml
Implement a version of `runDB` that doesn't do instrumentation so that `TestImport` and other users where instrumentation isn't appropriate do not have to fulfill the contract of `runDB`.
=> Add runDBSimple

freckle-app.cabal, library/Freckle/App.hs, library/Freckle/App/OpenTelemetry.hs, library/Freckle/App/OpenTelemetry/Wai.hs, library/Freckle/App/Test.hs, package.yaml, stack-lts-18.28.yaml, stack-lts-19.33.yaml, stack-nightly.yaml, stack.yaml, stack.yaml.lock
[bdc1cef](https://github.com/freckle/freckle-app/pull/97/commits/bdc1cefe1da3011b76910a79f345b20e3368ed07)
[b1d74b1](https://github.com/freckle/freckle-app/pull/97/commits/b1d74b1920c24e06a70ec516490db5584110be0c)
Discovered when upgrading megarepo/backend.
[4a259e2](https://github.com/freckle/freckle-app/pull/97/commits/4a259e2916b371c7edf8d7a6539e828b24d4eab1)
- Re-export some more types required to initialize
- Add `withTracerProviderXRayLogger`
- Export individual setters and `withTracerProvider`
=> Address some OTel omissions

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Ecs.hs, library/Freckle/App/Stats.hs, package.yaml
The first few commits increased visibility in the process further. The last commit actually fixes the bug:
[ace1f1d](https://github.com/freckle/freckle-app/pull/103/commits/ace1f1d6a1bc2154325c391d9ff035f0f79d3ddf)
At some point this started being a 404 with the trailing `/`. Removing
it gets things working again.
=> Extend debuggability and fix ECS Metadata

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Kafka/Consumer.hs, package.yaml
`progress-consumer` is segfaulting when deployed, but this change seems to fix it. Sleeping the main thread is suggested in the Immortal repo README: https://github.com/UnkindPartition/immortal
=> Sleep main thread to fix segfaulting

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Kafka/Consumer.hs, package.yaml
Manually committing offsets when processing messages might imply that something particular happens if committing an offset is skipped, such as the message being sent again by the broker. However, this is not usually the case: as soon as an offset for a later message is committed, a broker will not send an earlier skipped message in the topic partition.
Skipping messages is fine for the only application currently consuming messages using Kafka. In a future hypothetical application in which every message must be seen exactly or at least once, manually committing offsets is not sufficient due to the aforementioned behavior. There are strategies to rewind the offset in order to re-consume data, but they are currently beyond the scope of the needs for this library.
=> Auto-commit offsets

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Test/Yesod.hs, package.yaml, stack-lts-18.28.yaml, stack-lts-19.33.yaml, stack-nightly.yaml, stack.yaml, stack.yaml.lock
Enough has changed from https://github.com/freckle/freckle-app/pull/110 that I'm starting over with a new PR. Same gist; the main goals are
- Upstream our yesod testing utilities from megarepo so they can be shared.
- Make `YesodExample` actions polymorphic to reduce the amount of lifting required.
The proposed API is smaller this time because
- I've removed some superfluous utilities (e.g. `getOk`, `putOk`, `postOk`, `deleteOk`, ...) that have been removed from megarepo, as discussed in the previous PR.
- I've only bothered to include things that we're actually using.
Due to the reduced size, I've collapsed it all into one module this time.
A few more comments from the original PR may still warrant treatment.
=> add Freckle.App.Test.Yesod

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Test/Yesod.hs, package.yaml
=> Fix infinite recursion in ...Test.Yesod.getResponse

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Kafka/Consumer.hs, library/Freckle/App/OpenTelemetry.hs, library/Network/Wai/Middleware/OpenTelemetry.hs, package.yaml
[34671b2](https://github.com/freckle/freckle-app/pull/121/commits/34671b2cf78ffdd0aec3a68c8d7db5f08e2bbe1f)
This commit adds some functions to OpenTelemetry for working with the
current trace-id as converted to Datadog's format and for the purposes
of setting the log context. It's then re-used in the Middleware from
which it was extracted.
This will allow us to do the same thing in other persistent-process
runners, such as Kafka consumers, just like we do in APIs through the
middleware.
[98da8d6](https://github.com/freckle/freckle-app/pull/121/commits/98da8d6d5173937b0807920f7431718172f433b4)
This will ensure consumer logs all contain the current `trace_id`.
=> Ensure Kafka consumers include trace_id in log context

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Memcached.hs, library/Freckle/App/Memcached/CacheTTL.hs, library/Freckle/App/Memcached/MD5.hs, package.yaml
I'd like to be able to use some of this from megarepo/backend/core; it's currently in `entities`. Could move it to `core`, but might as well push it all the way out? There's a commit message indicating there was intent to upstream it; looks like it just never happened.
=> upstream Freckle.Memcached from megarepo/backend/entities

.github/workflows/ci.yml, library/Freckle/App/Database.hs, library/Freckle/App/Kafka/Consumer.hs, library/Freckle/App/Kafka/Producer.hs, library/Freckle/App/Memcached.hs, library/Freckle/App/Memcached/CacheKey.hs, library/Freckle/App/Memcached/CacheTTL.hs, library/Freckle/App/Memcached/Client.hs, library/Freckle/App/OpenTelemetry.hs, tests/Freckle/App/MemcachedSpec.hs
[b82b2d7](https://github.com/freckle/freckle-app/pull/125/commits/b82b2d7f2df83f23f84c6b56599023fdfd9e3782)
[02c522f](https://github.com/freckle/freckle-app/pull/125/commits/02c522f9ee2dd44c67e41d7bce04d1047155f374)
[6ee57d5](https://github.com/freckle/freckle-app/pull/125/commits/6ee57d5c5d1c913bf63a3c2b990c6337eb43e439)
[b4fe410](https://github.com/freckle/freckle-app/pull/125/commits/b4fe4109ac1cd0d01c77aaa051f5b95407cfa9ae)
[59f17ae](https://github.com/freckle/freckle-app/pull/125/commits/59f17ae01223924560e3aeec454f08234f3226b2)
This only adds topic name to the attributes, since how to deal with
multiple values and a keying function would be somewhat arbitrary. We'll
leave out that behavior for now and possibly add something later when we
start to use this and decide what we'd want. …
=> Add tracing to Memcached and Kafka operations

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Test/Hspec/Runner.hs, package.yaml
Uses `JUNIT_ENABLED` and other env vars to trigger and configure JUnit formatting when running tests, removing the legacy `CIRCLECI` env var. JUnit configuration is overridden to set the output path to `/tmp/junit` (existing behavior) and the source path prefix of the report, which is helpful in collecting test results in a monorepo.
=> Run tests with JUnit from env vars, if enabled

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Random.hs
For the sake of [Let Graphula tests select more than one random entity](https://app.asana.com/0/1205102828747541/1205920572323612). With this utility available, I think it should be easy enough enough to extend `Freckle.Test.Graphula.selectRandom` to randomly generating a set of row numbers and then select where `row_number()` is in the set.
=> Add Freckle.App.Random

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Memcached/Client.hs, library/Freckle/App/OpenTelemetry.hs, package.yaml
We attempt to add a `value` attribute to traces in caching, and we use
`decodeUtf8` to do so. We're encountering errors decoding some values as
UTF-8. These values in particular should decode fine, however the
library shouldn't be assuming that anyway. It should support any
`ByteString` value whatsoever. Failing here also prevents values from
being `set` at all, which can have drastic performance ramifications
that far outweigh the value of this observability-related feature.
To resolve specifically that, we use `decodeUtf8With lenientDecode`
instead. As part of that, we extract a dedicated function and also
implement a length limit, as these values could be any size. This also
gives us a handy place to document the situation.
=> Remove unsafe decodeUtf8 in cache tracing

CHANGELOG.md, library/Freckle/App/Exception/MonadThrow.hs, library/Freckle/App/Exception/MonadUnliftIO.hs
I missed a bunch of opportunities to add `withFrozenCallStack` earlier; this adds them to every definition in these modules.
Here's an example of what a snag looks like before this change.
After this change, the `throw` and `throwM` stack frames ought to disappear.
I've also done some eta expansions here; I'm not sure if they're necessary to make `withFrozenCallStack` work because I don't have a great intuition for how it works, but it seems more clear this way.
=> Use withFrozenCallStack on more exception utilities

.gitignore, CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Exception.hs, library/Freckle/App/Memcached.hs, library/Freckle/App/Prelude.hs, package.yaml, tests/Freckle/App/MemcachedSpec.hs
We're seeing a lot of `OpError ValueToLarge` errors from caching set operations. This isn't necessarily a problem, but it would be good to track down and perhaps break up whatever value is being cached. Adding `error.stack` will make that possible.
As part of this, I reduced the message log-level to `WARN` as that's what they are and how we treat them. Them appearing at `ERROR` level has confused a number of engineers.
=> Improve caching errors log messages

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Database.hs, library/Freckle/App/Test/Yesod.hs, package.yaml
https://app.asana.com/0/399653121150251/1206106385053669
An easy way to help get more call stack.
`MonadIO` has to promote to `MonadUnliftIO` to catch exceptions, which I think is what @pbrisbin once suggested the constraint should be in the first place.
=> checkpoint in liftSql

library/Freckle/App/Database.hs, library/Freckle/App/Stats.hs
- fix `active_pool_connections`
- start tracking `queries_enqueued_and_processing` where `active_pool_connections` was previously
=> Fix DB metrics

CHANGELOG.md, freckle-app.cabal, package.yaml, stack.yaml.lock
I missed the finishing touches required to publish this version.
=> publish v13

library/Freckle/App/Exception/MonadThrow.hs, library/Freckle/App/Exception/MonadUnliftIO.hs, library/Freckle/App/Kafka/Consumer.hs, library/Freckle/App/Yesod.hs
[412b74b](https://github.com/freckle/freckle-app/pull/143/commits/412b74bea264a5c892aff2878018c4de3d4fc716)
Because of how our catch functions work, this will be behavior neutral
if the exception is not annotated (with a minor improvement in the
structure of the logged error message), but if/once it *is* annotated,
we'll include an `error.stack` value.
[d066e12](https://github.com/freckle/freckle-app/pull/143/commits/d066e1235890af213e9e50c711c6a0297701d291)
Because of how our catch functions work, this will be behavior neutral
for exceptions that not annotated (with a minor improvement in the
structure of the logged error message), but if they *are* annotated,
we'll now include an `error.stack` value.
[187896d](https://github.com/freckle/freckle-app/pull/143/commits/187896d37d9c0a36ff734f …
=> Handle exceptions as annotated more

library/Freckle/App/Memcached/Client.hs
`fancy-api` will use `memcache` to store session data. As a result, we need to be able to require a memcache client.
By exposing the data constructors, we can extract a memcache client and continue on our merry way, or take another codebase if we do not have a client.
=> Expose 'MemcachedClient' data constructors.

CHANGELOG.md, freckle-app.cabal, hie.yaml, library/Freckle/App/Kafka/Consumer.hs, package.yaml
We were relying on `immortal` to handle the looping for `runConsumer` which calls the `onFinish` after every loop. This makes our strategy of calling a synchronous offset commit happen on every loop instead of just on error/shutdown of the consumer.
This changes to explicitly loop in the consumer so that `onFinish` only gets called on shutdown/crashes.
=> Explicitly loop in runConsumer

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Kafka/Consumer.hs, package.yaml
Our attempt to manually handle offset commits introduced a large performance regression. This reverts those changes and returns to the auto-commit strategy
This also sneaks in the change from https://github.com/freckle/freckle-app/commit/d4af9f3c1563b450f2a1554316652d3002335119 to explicitly loop in `runConsumer` instead of depending on `immortal` to bring up and down threads to do the looping.
=> Revert to auto-commit consumer strategy 

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Faktory/ProducerPool.hs, package.yaml
We should rely on a pool of connections to Faktory when  enqueueing jobs instead of opening new connections every time. This introduce a typeclass to abstract some of that.
=> Introduce FaktoryProducerPool 

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/OpenTelemetry.hs, package.yaml
This allows users of freckle-app to add arbitrary attributes to the
current span without having to otherwise import, or be aware of, the
OpenTelemetry library. This is particularly useful in middleware.
=> Add addCurrentSpanAttributes

library/Network/Wai/Middleware/Cors.hs
Because the middleware is designed to allow multiple possible origins,
by sending back the origin given as `Access-Control-Allowed-Origin` (if
it's valid), we need to ensure those responses aren't cached and served
to other origins, otherwise they will get CORS errors. Practically
speaking, the request `Origin` should factor into any cache-key.
According to the HTTP spec, you do this by including that header in
`Vary`, so that's what this change does.
Unfortunately, this may not always work. Fastly is known to work
correctly[^1] but CloudFront does not[^2]. For CloudFront, you also have
to configure your distribution itself to include `Origin` in the cache
key via your `CachePolicy`, and this `Vary` header is ignored.
[^1]: https://www.fastly.com/blog/getting-most-out-vary-fastly
[^2]: …
=> Add Vary: Origin to CORS response headers

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Kafka/Consumer.hs, library/Freckle/App/OpenTelemetry.hs, library/Freckle/App/OpenTelemetry/ThreadContext.hs, library/Freckle/App/Wai.hs, library/Network/Wai/Middleware/OpenTelemetry.hs, package.yaml
The existing OpenTelemetry modules here were careful to assume and
support Datadog as a backend. This was because we thought you had to in
order for it to function. That was either not the case, or is no longer
the case, as Datadog seems able to handle default id values and even
prefers to encode them as hex in its own UI. Converting ids to a
`Word64` value is no longer necessary, and actively confusing to see.
Because of this, we can simplify and remove some of our code here. This
change deprecates various things to nudge users a certain way when
upgrading.
=> Don't be Datadog-specific in OpenTelemetry module

CHANGELOG.md, freckle-app.cabal, library/Freckle/App.hs, library/Freckle/App/OpenTelemetry/Http.hs, package.yaml
This wraps all HTTP calls made within AppT with a span that includes a
name and attributes about the request and response. Individual functions
for generating names and attribute are also present, for use when making
similar instances.
=> Add automatic tracing to MonadHttp for AppT

library/Freckle/App/Http.hs
**Why?**
As far as I know there are currently 2 ways to use a non-`GET` request method:
1. including method in the request string (e.g. `parseRequest_ $ "POST " <> url`)
2. importing lower-level HTTP module and setting the field directly (e.g. `req { HTTP.method = "POST"}`)
**2** breaks the centralization we're providing with this module by requiring consumers to import an internal thing.
Also both of these are stringly typed, producing a runtime error if a mistake is made, exs. forgotten space, or casing:
> Note that the request method must be provided as all capital letters.
^ from `http-conduit`'s docs.
**Note**
We could just re-export `Network.HTTP.Simple (setRequestMethod)`, however, it still has the stringly-typed problem (it takes a `ByteString`). `StdMethod` gives us nice …
=> Add `Freckle.App.Http (setRequestMethod)`

CHANGELOG.md, freckle-app.cabal, library/Freckle/App/Test/Properties/PersistValue.hs, tests/Freckle/App/Test/Properties/PersistValueSpec.hs
Another assertion along the lines of JSON/PathPiece assertions. We test this occasionally in our monorepo.
=> Add test assertion for `PersistValue` round-trip

freckle-app/CHANGELOG.md, freckle-app/freckle-app.cabal, freckle-app/library/Freckle/App/Test/Yesod.hs, freckle-app/package.yaml
`getJsonBody` now just passes through to yesod-test, and `getCsvBody` is a copy of what that does.
I'm being lazy and skipping over the CSV content type check right now because I don't immediately know what the MIME type is or if we always set it correctly in our app.
=> improve getJsonBody error output

freckle-app/CHANGELOG.md, freckle-app/freckle-app.cabal, freckle-app/library/Freckle/App/Test/Hspec/AnnotatedException.hs, freckle-app/package.yaml, freckle-app/tests/Freckle/App/Test/Hspec/AnnotatedExceptionSpec.hs
This replicates a bunch of display logic from `displayException` in [annotated-exception](https://hackage.haskell.org/package/annotated-exception) that ideally would be exported by that package (cc @parsonsmatt).
Closes #201
=> improve exceptions rethrown by unwrapAnnotatedHUnitFailure

freckle-app/CHANGELOG.md, freckle-app/freckle-app.cabal, freckle-app/library/Freckle/App/Database.hs, freckle-app/package.yaml
Curious what y'all think of this idea - I'd like our traces to more explicitly show within `runDB` spans how much time is spent
- waiting on the connection pool; versus
- actually holding a connection.
The nicest way to display this would be to have a "waiting on the connection pool" span, but since the pool acquire is done by `persistent`, that doesn't seem super easy. Putting a span around the action, though, is trivial.
- Pro: When the reason for an action being slow was a long wait on the connection pool, that will appear clearly in its trace.
- Con: Maybe clutters up the traces a bit, since it adds a level of depth under every `runDB` which won't be super informative under normal performance.
=> runDB: add otel span for holding a database connection

.github/workflows/release.yml
We're not getting `freckle-app` haddocks on Hackage because the libpq dependency is making it fail to compile. If #159 really is fixed then I don't see the harm in just always uploading the docs.
=> always upload haddocks

freckle-app/freckle-app.cabal, freckle-app/library/Freckle/App/TextualEnum.hs, freckle-app/package.yaml, freckle-app/tests/Freckle/App/TextualEnumSpec.hs
This is an experiment that I'm putting out for review to see what the team thinks. I won't feel bad if we don't like it.
**What is it?**
`TextualEnum` is a `newtype` wrapper meant to provide a lot of boilerplate serialization/deserialization instances that we keep defining and redefining as we introduce new types and services.
**How's it work?**
The core idea is that if you can give your type an `Enum` instance, a `Bounded` instance, and a way to convert to text, then that should be enough to provide string-type (i.e. textual) representations of it.
So `toText` tells us how to serialize the value, and we can look through the `Bounded`/`Enum` instance values to parse it "from text".
`toText` is preferable from `fromText` because, for bounded/enums, totality is straightforward to …
=> Add `TextualEnum` `newtype` wrapper

persistent-sql-lifted/LICENSE, persistent-sql-lifted/package.yaml, persistent-sql-lifted/persistent-sql-lifted.cabal
Accidentally copied the version number from freckle-app instead of starting from zero. It accidentally didn't release anyway, so may as well fix it.
... also forgot to add the license.
=> fix version of persistent-sql-lifted

freckle-app/CHANGELOG.md, freckle-kafka/freckle-kafka.cabal, freckle-kafka/library/Freckle/App/Kafka/Consumer.hs, freckle-kafka/package.yaml
Adds a new `runConsumerBatched` so that we can start playing with batched kafka consumers to see if it can help throughput.
=> Add kafka batch consumer

freckle-http/library/Freckle/App/Test/Http.hs
`/port/` gets parsed as *port* in italics.
=> Fix haddock annoyance

freckle-app/CHANGELOG.md, freckle-app/freckle-app.cabal, freckle-app/library/Freckle/App/Async.hs, freckle-app/package.yaml
[d662ed6](https://github.com/freckle/freckle-app/pull/237/commits/d662ed62ae8a1dfacaa6d83cca73e3d08719e55a)
* Add some section headings
* Put functions we're overriding in the same order as their upstream
[32a81a4](https://github.com/freckle/freckle-app/pull/237/commits/32a81a4d5032cf16e12c91cc31f894e71201b6a4)
[303a77b](https://github.com/freckle/freckle-app/pull/237/commits/303a77b7575e113f2bb4c7eaa71bec77235f6fcf)
=> Add pooled varieties to Freckle.App.Async

freckle-app/CHANGELOG.md, freckle-app/package.yaml, freckle-http/library/Freckle/App/Http/Cache.hs, freckle-http/library/Freckle/App/Http/Cache/Memcached.hs, freckle-http/library/Freckle/App/Http/Cache/State.hs
The backend-agnostic cache logic encodes TTL into the cached data,
checks it on read, and ignores/deletes it if expired.
For a backend that supports expiry itself (e.g. memcached), this should
not be necessary. And, at times of heavy load, the extra `delete`
operations can cause performance problems.
To address this, we update the `set` member of `HttpCache` to accept the
TTL value too. Then, in the memcached implementation, we use it to set
with the key that TTL, meaning expired values will simply not be
retrieved by `get` at all, and no `delete`s will occur (modulo races).
We do still retain the backend-agnostic logic, since the state
implementation (for example) does not support expiring keys and so
expiration still needs to be checked externally for such backends.
Since the signature …
=> fix(freckle-http): use TTL in set operation
